"Ionian (Major)": [1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1]
"Dorian": [1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0]
"Phrygian": [1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0]
"Lydian": [1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1]
"Mixolydian": [1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0]
"Aeolian (Minor)": [1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0]
"Locrian": [1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0]