"Guitar: E Standard (6)": [4, 9, 2, 7, 11, 4]
"Guitar: D Standard (6)": [2, 7, 0, 5, 9, 2]
"Guitar: E Standard (8)": [6, 11, 4, 9, 2, 7, 11, 4]
"Guitar: D Standard (8)": [4, 9, 2, 7, 0, 5, 9, 2]
"Violin": [7, 2, 9, 4]