"Guitar: E6": [4, 9, 2, 7, 11, 4]
"Guitar: D6": [2, 7, 0, 5, 9, 2]
"Guitar: E8": [6, 11, 4, 9, 2, 7, 11, 4]
"Guitar: Eb8": [5, 10, 3, 8, 1, 6, 10, 3]
"Guitar: D8": [4, 9, 2, 7, 0, 5, 9, 2]
"Guitar: D7": [4, 9, 2, 7, 0, 5, 9]
"Violin": [7, 2, 9, 4]
"Bass E4": [4, 9, 2, 7]
"Bass E5": [11, 4, 9, 2, 7]
"Bass E6": [11, 4, 9, 2, 7, 0]
"Bass D6": [9, 2, 7, 0, 5, 10]